import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kpran
 */
@SuppressWarnings("serial")
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Display
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        jLabel4.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - Student Record System");
        setExtendedState(JFrame.NORMAL);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<HTML><U>Student Record System</U></HTML>");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter SQL Password");

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setMnemonic('L');
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setMnemonic('S');
        jButton2.setText("Show Records");
        jButton2.setVisible(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setMnemonic('A');
        jButton3.setText("Add New Record");
        jButton3.setVisible(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setMnemonic('U');
        jButton4.setText("Update Records");
        jButton4.setVisible(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setMnemonic('D');
        jButton5.setText("Delete Records");
        jButton5.setVisible(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton6.setMnemonic('O');
        jButton6.setText("Log Out");
        jButton6.setVisible(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboBox1.setVisible(false);

        jScrollPane1.setVisible(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tables"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Select table to manage:");
        jLabel3.setVisible(false);

        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton7.setMnemonic('N');
        jButton7.setText("Add New Table");
        jButton7.setVisible(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton8.setMnemonic('R');
        jButton8.setText("Rename Table");
        jButton8.setVisible(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton9.setMnemonic('T');
        jButton9.setText("Delete Table");
        jButton9.setVisible(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton6))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s=new String(jPasswordField1.getPassword());
        DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
        try
        {   Class.forName("java.sql.Driver");
            Connection con1=DriverManager.getConnection("jdbc:mysql://localhost", "root", s);
            JOptionPane.showMessageDialog(null, "Login Successful !!!", "Welcome", JOptionPane.INFORMATION_MESSAGE);
            this.setTitle("Home - Student Record System");
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            jLabel4.setText("0");
            jPasswordField1.setEnabled(false);
            jButton1.setEnabled(false);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jButton4.setVisible(true);
            jButton5.setVisible(true);
            jButton6.setVisible(true);
            jButton7.setVisible(true);
            jButton8.setVisible(true);
            jButton9.setVisible(true);
            jScrollPane1.setVisible(true);
            jLabel3.setVisible(true);
            jComboBox1.setVisible(true);
            Statement stmt1=con1.createStatement();
            String qry1="show databases;";
            ResultSet rs1=stmt1.executeQuery(qry1);
            int db=0;
            while(rs1.next())
            {   if(rs1.getString(1).equalsIgnoreCase("School"))
                {   db++;
                    break;
                }
            }
            rs1.close();
            stmt1.close();
            if(db==0)
            {   Statement stmt2=con1.createStatement();
                String dbase="create database School;";
                stmt2.executeUpdate(dbase);
                JOptionPane.showMessageDialog(null, "School database not found.\n\nCreated", "Database Error", JOptionPane.INFORMATION_MESSAGE);
                stmt2.close();
            }
            con1.close();
            Connection con2=DriverManager.getConnection("jdbc:mysql://localhost/School", "root", s);
            Statement stmt3=con2.createStatement();
            String qry2="show tables;";
            ResultSet rs2=stmt3.executeQuery(qry2);
            dtm.setRowCount(0);
            jComboBox1.removeAllItems();
            while(rs2.next())
            {   String tab=rs2.getString(1);
                dtm.addRow(new Object[] {tab});
                jComboBox1.addItem(tab);
            }
            if(dtm.getRowCount()==0)
            {   jButton2.setEnabled(false);
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
                jButton5.setEnabled(false);
                jButton8.setEnabled(false);
                jButton9.setEnabled(false);
                if(db!=0)
                {   JOptionPane.showMessageDialog(null, "No Tables Found !!!", "Table Error", JOptionPane.WARNING_MESSAGE);}
            }
            rs2.close();
            stmt3.close();
            con2.close();
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {   String err=String.valueOf(Integer.parseInt(jLabel4.getText())+1);
            JOptionPane.showMessageDialog(null, "Incorrect Password\n\nFailure Attempt "+err, "Login Error", JOptionPane.ERROR_MESSAGE);
            jPasswordField1.setText(null);
            jLabel4.setText(err);
            if(Integer.parseInt(err)%5==0)
            {   jPasswordField1.setEnabled(false);
                jButton1.setEnabled(false);
                this.setTitle("Login (Blocked) - Student Record System");
                long t=System.currentTimeMillis();
                if(err.equals("5")||err.equals("10"))
                {   JOptionPane.showMessageDialog(null, "Too many failure login attempts.\n\nBlocking for 20 seconds", "Login Error", JOptionPane.ERROR_MESSAGE);
                    while(System.currentTimeMillis()-t<20000)
                    {}
                }
                else if(err.equals("15"))
                {   JOptionPane.showMessageDialog(null, "Too many failure login attempts.\n\nBlocked", "Login Error", JOptionPane.ERROR_MESSAGE);
                    while(System.currentTimeMillis()-t>=0)
                    {}
                }
                jPasswordField1.setEnabled(true);
                jButton1.setEnabled(true);
                this.setTitle("Login - Student Record System");
                JOptionPane.showMessageDialog(null, "You can now log in", "Login", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String p=new String(jPasswordField1.getPassword());
        String t=(String) jComboBox1.getSelectedItem();
        Display disp=new Display(p, t);
        disp.setVisible(true);
        disp.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String s=new String(jPasswordField1.getPassword());
        String t=(String) jComboBox1.getSelectedItem();
        try
        {   String roll=JOptionPane.showInputDialog("Enter Roll No.");
            String n=JOptionPane.showInputDialog("Enter Name");
            String contact=JOptionPane.showInputDialog("Enter Contact No.");
            String a=JOptionPane.showInputDialog("Enter Locality");
            String sub1=JOptionPane.showInputDialog("Enter Physics Marks");
            String sub2=JOptionPane.showInputDialog("Enter Chemistry Marks");
            String sub3=JOptionPane.showInputDialog("Enter Mathematics Marks");
            String sub4=JOptionPane.showInputDialog("Enter IP Marks");
            String sub5=JOptionPane.showInputDialog("Enter English Marks");
            if (roll.isEmpty())
            {   JOptionPane.showMessageDialog(null, "Roll No. not entered", "Record Error", JOptionPane.WARNING_MESSAGE);}
            else if (contact.isEmpty())
            {   JOptionPane.showMessageDialog(null, "Contact No. not entered", "Record Error", JOptionPane.WARNING_MESSAGE);}
            else if (sub1.isEmpty())
            {   JOptionPane.showMessageDialog(null, "Physics Marks not entered", "Record Error", JOptionPane.WARNING_MESSAGE);}
            else if (sub2.isEmpty())
            {   JOptionPane.showMessageDialog(null, "Chemistry Marks not entered", "Record Error", JOptionPane.WARNING_MESSAGE);}
            else if (sub3.isEmpty())
            {   JOptionPane.showMessageDialog(null, "Mathematics Marks not entered", "Record Error", JOptionPane.WARNING_MESSAGE);}
            else if (sub4.isEmpty())
            {   JOptionPane.showMessageDialog(null, "IP Marks not entered", "Record Error", JOptionPane.WARNING_MESSAGE);}
            else if (sub5.isEmpty())
            {   JOptionPane.showMessageDialog(null, "English Marks not entered", "Record Error", JOptionPane.WARNING_MESSAGE);}
            else
            {   Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost/School", "root", s);
                Statement stmt=con.createStatement();
                int r=Integer.parseInt(roll);
                long c=Long.parseLong(contact);
                int s1=Integer.parseInt(sub1);
                int s2=Integer.parseInt(sub2);
                int s3=Integer.parseInt(sub3);
                int s4=Integer.parseInt(sub4);
                int s5=Integer.parseInt(sub5);
                String qry=("insert into "+t+" values ("+r+", \""+n+"\", "+c+", \""+a+"\", "+s1+", "+s2+", "+s3+", "+s4+", "+s5+");");
                stmt.executeUpdate(qry);
                JOptionPane.showMessageDialog(null, "Record Added Successfully", "Add", JOptionPane.INFORMATION_MESSAGE);
                stmt.close();
                con.close();
            }
        }
        catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
        {   if(e.getMessage().startsWith("Duplicate entry"))
            {   JOptionPane.showMessageDialog(null, "Record already exists for this roll no.", "Duplicate Record", JOptionPane.INFORMATION_MESSAGE);}
            else if(e.getMessage().startsWith("For input string"))
            {   JOptionPane.showMessageDialog(null, "Record not added.\n\nInvalid value(s) entered", "Record Error", JOptionPane.WARNING_MESSAGE);}
        }
        catch (NullPointerException x)
        {   JOptionPane.showMessageDialog(null, "Record not added. Aborted by user", "Add", JOptionPane.INFORMATION_MESSAGE);}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int q=JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Log Out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (q==JOptionPane.YES_OPTION)
        {   JOptionPane.showMessageDialog(null, "Logged Out Successfully !!!", "Log Out", JOptionPane.INFORMATION_MESSAGE);
            jPasswordField1.setEnabled(true);
            jPasswordField1.setText(null);
            jButton1.setEnabled(true);
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
            jButton6.setVisible(false);
            jButton7.setVisible(false);
            jButton8.setVisible(false);
            jButton9.setVisible(false);
            jScrollPane1.setVisible(false);
            jLabel3.setVisible(false);
            jComboBox1.setVisible(false);
            this.setTitle("Login - Student Record System");
            this.setExtendedState(JFrame.NORMAL);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String p=new String(jPasswordField1.getPassword());
        String t=(String) jComboBox1.getSelectedItem();
        Delete del=new Delete(p, t);
        del.setVisible(true);
        del.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String p=new String(jPasswordField1.getPassword());
        String t=(String) jComboBox1.getSelectedItem();
        Update up=new Update(p, t);
        up.setVisible(true);
        up.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String s=new String(jPasswordField1.getPassword());
        DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
        try
        {   String tname=JOptionPane.showInputDialog("Enter Table Name");
            if (tname.isEmpty())
            {   JOptionPane.showMessageDialog(null, "Table name cannot be empty", "Table Error", JOptionPane.WARNING_MESSAGE);}
            else
            {   Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost/School", "root", s);
                Statement stmt=con.createStatement();
                String qry="create table "+tname+" (Roll_No int(3) primary key, Name varchar(25) not null, Contact_No bigint(11), Locality varchar(50), Phy_Marks int(3), Chem_Marks int(3), Math_Marks int(3), IP_Marks int(3), Eng_Marks int(3));";
                stmt.executeUpdate(qry);
                JOptionPane.showMessageDialog(null, "Table Created Successfully !!!", "Table", JOptionPane.INFORMATION_MESSAGE);
                dtm.addRow(new Object[] {tname});
                jComboBox1.addItem(tname);
                jButton2.setEnabled(true);
                jButton3.setEnabled(true);
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jButton8.setEnabled(true);
                jButton9.setEnabled(true);
            }
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {   if (e.getMessage().startsWith("You have an error in your SQL syntax"))
            {   JOptionPane.showMessageDialog(null, "Invalid Table Name", "Table Error", JOptionPane.WARNING_MESSAGE);}
            else if (e.getMessage().startsWith("Table"))
            {   JOptionPane.showMessageDialog(null, "Table Already Exists", "Duplicate Table Name", JOptionPane.INFORMATION_MESSAGE);}
        }
        catch(NullPointerException x)
        {   JOptionPane.showMessageDialog(null, "Table not created. Aborted by user", "Table", JOptionPane.INFORMATION_MESSAGE);}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String s=new String(jPasswordField1.getPassword());
        DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
        String tname=(String) jComboBox1.getSelectedItem();
        try
        {   String newtable=JOptionPane.showInputDialog(null, "Enter new table name", "Rename Table", JOptionPane.QUESTION_MESSAGE);
            if (newtable.isEmpty())
            {   JOptionPane.showMessageDialog(null, "Table name cannot be empty", "Table Error", JOptionPane.WARNING_MESSAGE);}
            else
            {   Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost/School", "root", s);
                Statement stmt1=con.createStatement();
                String qry1="rename table "+tname+" to "+newtable+";";
                stmt1.executeUpdate(qry1);
                JOptionPane.showMessageDialog(null, "Table Renamed Successfully !!!", "Table", JOptionPane.INFORMATION_MESSAGE);
                stmt1.close();
                Statement stmt2=con.createStatement();
                String qry2="show tables;";
                ResultSet rs=stmt2.executeQuery(qry2);
                dtm.setRowCount(0);
                jComboBox1.removeAllItems();
                while(rs.next())
                {   String tab=rs.getString(1);
                    dtm.addRow(new Object[] {tab});
                    jComboBox1.addItem(tab);
                }
                rs.close();
                stmt2.close();
            }
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {   if (e.getMessage().startsWith("You have an error in your SQL syntax"))
            {   JOptionPane.showMessageDialog(null, "Invalid Table Name", "Table Error", JOptionPane.WARNING_MESSAGE);}
            else if (e.getMessage().startsWith("Table"))
            {   JOptionPane.showMessageDialog(null, "Table Already Exists", "Duplicate Table Name", JOptionPane.INFORMATION_MESSAGE);}
        }
        catch(NullPointerException x)
        {   JOptionPane.showMessageDialog(null, "Table not renamed. Aborted by user", "Rename Table", JOptionPane.INFORMATION_MESSAGE);}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String s=new String(jPasswordField1.getPassword());
        DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
        int q=JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the table?", "Delete Table", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (q==JOptionPane.YES_OPTION)
        {   String tname=(String) jComboBox1.getSelectedItem();
            try
            {   Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost/School", "root", s);
                Statement stmt1=con.createStatement();
                String qry1="drop table "+tname+";";
                stmt1.executeUpdate(qry1);
                JOptionPane.showMessageDialog(null, "Table Deleted Successfully !!!", "Table", JOptionPane.INFORMATION_MESSAGE);
                stmt1.close();
                Statement stmt2=con.createStatement();
                String qry2="show tables;";
                ResultSet rs=stmt2.executeQuery(qry2);
                dtm.setRowCount(0);
                jComboBox1.removeAllItems();
                while(rs.next())
                {   String tab=rs.getString(1);
                    dtm.addRow(new Object[] {tab});
                    jComboBox1.addItem(tab);
                }
                if(dtm.getRowCount()==0)
                {   jButton2.setEnabled(false);
                    jButton3.setEnabled(false);
                    jButton4.setEnabled(false);
                    jButton5.setEnabled(false);
                    jButton8.setEnabled(false);
                    jButton9.setEnabled(false);
                    JOptionPane.showMessageDialog(null, "No Tables Found !!!", "Table Error", JOptionPane.WARNING_MESSAGE);
                }
                rs.close();
                stmt2.close();
            }
            catch(HeadlessException | ClassNotFoundException | SQLException e)
            {   JOptionPane.showMessageDialog(null, e.getMessage());}
        }
        else
        {   JOptionPane.showMessageDialog(null, "Table not deleted. Aborted by user", "Delete Table", JOptionPane.INFORMATION_MESSAGE);}
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
